$script = <<-SCRIPT

softwareupdate --all --install --force

# Install Homebrew; @see https://brew.sh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

# Install minimal complement of tools
brew install awscli aws-iam-authenticator azure-cli docker git gpg graphviz libressl mkcert nss openssl terraform terraform-docs tflint httpie kind kubernetes-cli kubeseal helm helmfile krew octant pv
brew install --cask google-cloud-sdk
brew install --cask keybase
brew tap vmware-tanzu/carvel
brew install ytt kbld kapp imgpkg kwt vendir
brew install derailed/k9s/k9s
brew install cloudfoundry/tap/bosh-cli
brew install pivotal/tap/pivnet-cli
brew install cloudfoundry/tap/cf-cli@7
brew install kn
brew tap argoproj/tap
brew install argoproj/tap/argo
brew install argoproj/tap/argocd
brew install argoproj/tap/kubectl-argo-rollouts
brew tap tektoncd/tools
brew install tektoncd/tools/tektoncd-cli
brew install minio/stable/mc
brew install --cask visual-studio-code
brew install buildpacks/tap/pack
brew install java11
brew install tilt-dev/tap/tilt
brew install podman
brew install velero
brew install oci-cli

OM_VERSION=7.4.1
curl -LO https://github.com/pivotal-cf/om/releases/download/${OM_VERSION}/om-darwin-${OM_VERSION} && \
mv om-darwin-${OM_VERSION} om && \
chmod +x om && \
sudo mv om /usr/local/bin && \

TMC_VERSION=0.4.0-fdabbe74 && \
curl -LO https://tmc-cli.s3-us-west-2.amazonaws.com/tmc/${TMC_VERSION}/darwin/x64/tmc && \
chmod +x tmc && \
sudo mv tmc /usr/local/bin

if [ -e "/Users/vagrant/tanzu" ]; then
  sudo chmod +x /Users/vagrant/tanzu
  sudo mv /Users/vagrant/tanzu /usr/local/bin
fi

if [ -e "/Users/vagrant/tanzu-cli-bundle-darwin-amd64.tar" ]; then
  tar xvf tanzu-cli-bundle-darwin-amd64.tar -C .
  tanzu plugin clean
  tanzu plugin install --local cli all
  rm -Rf cli tanzu-cli-bundle-darwin-amd64.tar
fi
chmod +x *.sh

SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "VMR/MacOS_Catalina-R"
  config.disksize.size = '50GB'
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |v|
    v.check_guest_additions = false
    v.memory = 8192
    v.cpus = 2
  end
  config.vm.provision "file", source: "dist", destination: "/Users/vagrant"
  config.vm.provision "file", source: "inventory.sh", destination: "/Users/vagrant/inventory.sh"
  config.vm.provision "file", source: "fetch-tanzu-cli.sh", destination: "/Users/vagrant/fetch-tanzu-cli.sh"
  config.vm.provision "file", source: "fetch-and-install-oci-cli.sh", destination: "/Users/vagrant/fetch-and-install-oci-cli.sh"
  config.vm.provision "shell", inline: $script, privileged: false
end