Vagrant.configure("2") do |config|
  config.vm.box = "VMR/MacOS_Catalina-R"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |v|
    v.check_guest_additions = false
  end
end