apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: custom
spec:
  order:
  - group:
    - id: tanzu-buildpacks/dotnet-core
  - group:
    - id: tanzu-buildpacks/nodejs
  - group:
    - id: tanzu-buildpacks/go
  - group:
    - id: tanzu-buildpacks/python
  - group:
    - id: tanzu-buildpacks/php
  - group:
    - id: tanzu-buildpacks/nginx
  - group:
    - id: tanzu-buildpacks/httpd
  - group:
    - id: tanzu-buildpacks/java-native-image
  - group:
    - id: tanzu-buildpacks/java
  - group:
    - id: paketo-buildpacks/ruby
  - group:
    - id: paketo-buildpacks/procfile
  serviceAccountRef:
    name: kp-default-repository-serviceaccount
    namespace: kpack
  stack:
    kind: ClusterStack
    name: full
  store:
    kind: ClusterStore
    name: default
  tag: replace.me/replace.me/replace.me:clusterbuilder-full
status:
  builderMetadata:
  - homepage: https://github.com/paketo-buildpacks/bellsoft-liberica
    id: paketo-buildpacks/bellsoft-liberica
    version: 9.0.2
  - id: tanzu-buildpacks/go-dist
    version: 0.6.5
  - id: tanzu-buildpacks/php-dist
    version: 0.3.3
  - homepage: https://github.com/pivotal-cf/tanzu-cpython
    id: tanzu-buildpacks/cpython
    version: 0.2.0
  - id: tanzu-buildpacks/dotnet-core-sdk
    version: 0.3.1
  - id: tanzu-buildpacks/node-engine
    version: 0.8.3
  - homepage: https://github.com/pivotal-cf/tanzu-apache-skywalking
    id: tanzu-buildpacks/apache-skywalking
    version: 4.1.2
  - id: tanzu-buildpacks/dotnet-core-runtime
    version: 0.3.1
  - homepage: https://github.com/pivotal-cf/tanzu-appdynamics
    id: tanzu-buildpacks/appdynamics
    version: 4.2.0
  - homepage: https://github.com/pivotal-cf/tanzu-appdynamics
    id: tanzu-buildpacks/appdynamics
    version: 4.1.4
  - homepage: https://github.com/paketo-buildpacks/gradle
    id: paketo-buildpacks/gradle
    version: 6.0.2
  - homepage: https://github.com/pivotal-cf/tanzu-jprofiler
    id: tanzu-buildpacks/jprofiler
    version: 4.0.2
  - homepage: https://github.com/pivotal-cf/tanzu-miniconda
    id: tanzu-buildpacks/miniconda
    version: 0.1.4
  - homepage: https://github.com/pivotal-cf/tanzu-new-relic
    id: tanzu-buildpacks/new-relic
    version: 4.1.0
  - homepage: https://github.com/pivotal-cf/tanzu-new-relic
    id: tanzu-buildpacks/new-relic
    version: 4.0.4
  - homepage: https://github.com/pivotal-cf/tanzu-overops
    id: tanzu-buildpacks/overops
    version: 4.0.3
  - homepage: https://github.com/pivotal-cf/tanzu-pipenv
    id: tanzu-buildpacks/pipenv
    version: 0.2.4
  - id: tanzu-buildpacks/dotnet-core-aspnet
    version: 0.3.2
  - homepage: https://github.com/paketo-buildpacks/maven
    id: paketo-buildpacks/maven
    version: 6.1.0
  - homepage: https://github.com/paketo-buildpacks/apache-tomcat
    id: paketo-buildpacks/apache-tomcat
    version: 7.0.3
  - id: tanzu-buildpacks/icu
    version: 0.0.13
  - homepage: https://github.com/paketo-buildpacks/azure-application-insights
    id: paketo-buildpacks/azure-application-insights
    version: 5.1.2
  - homepage: https://github.com/pivotal-cf/tanzu-jrebel
    id: tanzu-buildpacks/jrebel
    version: 4.0.3
  - homepage: https://github.com/paketo-buildpacks/sbt
    id: paketo-buildpacks/sbt
    version: 6.1.0
  - homepage: https://github.com/paketo-buildpacks/sbt
    id: paketo-buildpacks/sbt
    version: 6.0.4
  - homepage: https://github.com/pivotal-cf/tanzu-riverbed
    id: tanzu-buildpacks/riverbed
    version: 4.0.2
  - homepage: https://github.com/pivotal-cf/tanzu-yourkit
    id: tanzu-buildpacks/yourkit
    version: 4.0.3
  - homepage: https://docs.pivotal.io/tanzu-buildpacks/httpd/httpd-buildpack.html
    id: tanzu-buildpacks/httpd
    version: 0.3.4
  - homepage: https://docs.pivotal.io/tanzu-buildpacks/nginx/nginx-buildpack.html
    id: tanzu-buildpacks/nginx
    version: 0.4.4
  - homepage: https://github.com/pivotal-cf/tanzu-pip
    id: tanzu-buildpacks/pip
    version: 0.6.3
  - homepage: https://github.com/pivotal-cf/tanzu-contrast-security
    id: tanzu-buildpacks/contrast-security
    version: 4.1.1
  - homepage: https://github.com/pivotal-cf/tanzu-elastic-apm
    id: tanzu-buildpacks/elastic-apm
    version: 4.1.2
  - homepage: https://github.com/paketo-buildpacks/maven
    id: paketo-buildpacks/maven
    version: 6.0.2
  - homepage: https://github.com/paketo-buildpacks/google-stackdriver
    id: paketo-buildpacks/google-stackdriver
    version: 5.1.2
  - homepage: https://github.com/pivotal-cf/tanzu-elastic-apm
    id: tanzu-buildpacks/elastic-apm
    version: 4.1.3
  - id: tanzu-buildpacks/dep
    version: 0.1.4
  - homepage: https://github.com/paketo-buildpacks/syft
    id: paketo-buildpacks/syft
    version: 1.3.1
  - id: tanzu-buildpacks/php-web
    version: 0.1.4
  - id: tanzu-buildpacks/php-composer
    version: 0.1.10
  - id: tanzu-buildpacks/yarn
    version: 0.3.3
  - homepage: https://github.com/pivotal-cf/tanzu-dynatrace
    id: tanzu-buildpacks/dynatrace
    version: 4.0.2
  - homepage: https://github.com/paketo-buildpacks/spring-boot
    id: paketo-buildpacks/spring-boot
    version: 5.3.0
  - homepage: https://github.com/pivotal-cf/tanzu-jacoco
    id: tanzu-buildpacks/jacoco
    version: 4.0.2
  - id: tanzu-buildpacks/node-module-bom
    version: 0.1.4
  - homepage: https://github.com/pivotal-cf/tanzu-checkmarx
    id: tanzu-buildpacks/checkmarx
    version: 4.0.2
  - homepage: https://github.com/paketo-buildpacks/watchexec
    id: paketo-buildpacks/watchexec
    version: 2.0.2
  - homepage: https://github.com/paketo-buildpacks/upx
    id: paketo-buildpacks/upx
    version: 3.0.1
  - homepage: https://github.com/pivotal-cf/tanzu-synopsys
    id: tanzu-buildpacks/synopsys
    version: 4.0.2
  - homepage: https://github.com/paketo-buildpacks/ca-certificates
    id: paketo-buildpacks/ca-certificates
    version: 3.0.2
  - homepage: https://github.com/paketo-buildpacks/procfile
    id: paketo-buildpacks/procfile
    version: 5.0.2
  - homepage: https://github.com/paketo-buildpacks/encrypt-at-rest
    id: paketo-buildpacks/encrypt-at-rest
    version: 4.0.2
  - homepage: https://github.com/paketo-buildpacks/leiningen
    id: paketo-buildpacks/leiningen
    version: 4.0.2
  - homepage: https://github.com/paketo-buildpacks/clojure-tools
    id: paketo-buildpacks/clojure-tools
    version: 2.0.2
  - homepage: https://github.com/paketo-buildpacks/syft
    id: paketo-buildpacks/syft
    version: 1.4.0
  - homepage: https://github.com/pivotal-cf/tanzu-snyk
    id: tanzu-buildpacks/snyk
    version: 4.0.2
  - id: tanzu-buildpacks/go-build
    version: 0.3.2
  - id: tanzu-buildpacks/dotnet-publish
    version: 0.5.1
  - id: tanzu-buildpacks/dotnet-execute
    version: 0.4.1
  - homepage: https://github.com/pivotal-cf/tanzu-pipenv-install
    id: tanzu-buildpacks/pipenv-install
    version: 0.1.6
  - id: tanzu-buildpacks/npm-install
    version: 0.5.3
  - id: tanzu-buildpacks/yarn-install
    version: 0.3.2
  - id: tanzu-buildpacks/dep-ensure
    version: 0.1.3
  - id: tanzu-buildpacks/go-mod-vendor
    version: 0.2.3
  - homepage: https://github.com/pivotal-cf/tanzu-pip-install
    id: tanzu-buildpacks/pip-install
    version: 0.2.2
  - homepage: https://github.com/pivotal-cf/tanzu-conda-env-update
    id: tanzu-buildpacks/conda-env-update
    version: 0.1.4
  - id: tanzu-buildpacks/node-run-script
    version: 0.2.2
  - id: tanzu-buildpacks/npm-start
    version: 0.2.3
  - id: tanzu-buildpacks/yarn-start
    version: 0.2.3
  - homepage: https://github.com/pivotal-cf/tanzu-python-start
    id: tanzu-buildpacks/python-start
    version: 0.4.2
  - id: tanzu-buildpacks/node-start
    version: 0.3.3
  - homepage: https://github.com/paketo-buildpacks/native-image
    id: paketo-buildpacks/native-image
    version: 5.0.2
  - homepage: https://github.com/paketo-buildpacks/executable-jar
    id: paketo-buildpacks/executable-jar
    version: 6.0.2
  - homepage: https://github.com/pivotal-cf/tanzu-aspectj
    id: tanzu-buildpacks/aspectj
    version: 4.0.2
  - homepage: https://github.com/paketo-buildpacks/dist-zip
    id: paketo-buildpacks/dist-zip
    version: 5.0.2
  - homepage: https://github.com/paketo-buildpacks/environment-variables
    id: paketo-buildpacks/environment-variables
    version: 4.0.1
  - homepage: https://github.com/paketo-buildpacks/environment-variables
    id: paketo-buildpacks/environment-variables
    version: 4.0.2
  - homepage: https://github.com/paketo-buildpacks/image-labels
    id: paketo-buildpacks/image-labels
    version: 4.0.2
  - homepage: https://github.com/pivotal-cf/tanzu-java
    id: tanzu-buildpacks/java
    version: 6.4.0
  - homepage: https://github.com/pivotal-cf/tanzu-java-native-image
    id: tanzu-buildpacks/java-native-image
    version: 6.5.0
  - homepage: https://docs.pivotal.io/tanzu-buildpacks/nodejs/nodejs-buildpack.html
    id: tanzu-buildpacks/nodejs
    version: 1.13.5
  - homepage: https://docs.pivotal.io/tanzu-buildpacks/dotnet-core/dotnet-core-buildpack.html
    id: tanzu-buildpacks/dotnet-core
    version: 1.11.1
  - homepage: https://docs.pivotal.io/tanzu-buildpacks/go/go-buildpack.html
    id: tanzu-buildpacks/go
    version: 1.10.4
  - homepage: https://docs.pivotal.io/tanzu-buildpacks/php/php-buildpack.html
    id: tanzu-buildpacks/php
    version: 0.7.9
  - homepage: https://github.com/paketo-buildpacks/ruby
    id: paketo-buildpacks/ruby
    version: 0.10.0
  - id: tanzu-buildpacks/python
    version: 1.1.4
  latestImage: replace.me/replace.me/replace.me:clusterbuilder-full@sha256:3727836eae74df75a11209298a49cc9d921e0195cd7a3ed404d5f7083d0e9578
  order:
  - group:
    - id: tanzu-buildpacks/dotnet-core
      version: 1.11.1
  - group:
    - id: tanzu-buildpacks/nodejs
      version: 1.13.5
  - group:
    - id: tanzu-buildpacks/go
      version: 1.10.4
  - group:
    - id: tanzu-buildpacks/python
      version: 1.1.4
  - group:
    - id: tanzu-buildpacks/php
      version: 0.7.9
  - group:
    - id: tanzu-buildpacks/nginx
      version: 0.4.4
  - group:
    - id: tanzu-buildpacks/httpd
      version: 0.3.4
  - group:
    - id: tanzu-buildpacks/java-native-image
      version: 6.5.0
  - group:
    - id: tanzu-buildpacks/java
      version: 6.4.0
  - group:
    - id: paketo-buildpacks/ruby
      version: 0.10.0
  - group:
    - id: paketo-buildpacks/procfile
      version: 5.0.2
  os: linux
  stack:
    id: io.buildpacks.stacks.bionic
    runImage: replace.me/replace.me/replace.me@sha256:50bf5cfa29e72dad0be184817a0a163f4a972c73da59b43b0dbf28d522e5e7cd