
Write-Output "Argo CD CLI" && argocd version && Write-Output ""
Write-Output "Argo Workflows CLI" && argo version && Write-Output ""
Write-Output "Azure CLI" && az version && Write-Output ""
Write-Output "AWS CLI" && aws --version && Write-Output ""
Write-Output "AWS IAM Authenticator" && aws-iam-authenticator version && Write-Output ""
Write-Output "BOSH CLI" && bosh --version && Write-Output ""
Write-Output "Cloud Foundry CLI" && cf --version && Write-Output ""
Write-Output "Credhub CLI" && credhub --version && Write-Output ""
Write-Output "curl" && curl --version && Write-Output ""
Write-Output "Google Cloud SDK" && gcloud version && Write-Output ""
Write-Output "Github CLI" && gh version && Write-Output ""
Write-Output "git" && git --version && Write-Output ""
Write-Output "Go" && go version && Write-Output ""
Write-Output "Helm" && helm version && Write-Output ""
Write-Output "Helm File" && helmfile version && Write-Output ""
Write-Output "HTTPie" && http --version && Write-Output ""
Write-Output "Carvel imgpkg" && imgpkg version && Write-Output ""
Write-Output "Java" && java --version && Write-Output ""
Write-Output "JSON Query (jq)" && jq --version && Write-Output ""
Write-Output "K9s" && k9s version && Write-Output ""
Write-Output "Carvel kapp" && kapp version && Write-Output ""
Write-Output "Carvel kwt" && kwt version && Write-Output ""
Write-Output "Krew, the package manager for kubectl plugins" && krew version && Write-Output ""
Write-Output "kubectl" && kubectl version && Write-Output ""
Write-Output "mkcert" && mkcert --version && Write-Output ""
Write-Output "VMware Tanzu Ops Manager CLI" && om version && Write-Output ""
Write-Output "Open SSL" && openssl version && Write-Output ""
Write-Output "Node JS" && node --version && Write-Output ""
Write-Output "Node Package Manager" && npm version && Write-Output ""
Write-Output "Cloud Native Buildpacks CLI" && pack --version && Write-Output ""
Write-Output "Tanzu Network CLI" && pivnet version && Write-Output ""
Write-Output "Tekton CD CLI" && tkn version && Write-Output ""
Write-Output "Hashicorp Terraform CLI" && terraform version && Write-Output ""
Write-Output "Public Cloud Resources Clean-up Utility (leftovers)" && leftovers --version && Write-Output ""
Write-Output "Tanzu CLI" && tanzu version && Write-Output ""
Write-Output "Tanzu Mission Control CLI" && tmc version && Write-Output ""
Write-Output "CloudFoundry UAA CLI" && uaac --version && Write-Output ""
Write-Output "Carvel vendir" && vendir version && Write-Output ""
Write-Output "Carvel ytt" && ytt version && Write-Output ""
