name: Build Ubuntu 20.04 VM Image on AWS

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use copy-file-action
        uses: canastro/copy-file-action@master

      - name: Copy init.sh
        with:
          source: "scripts/init.sh"
          target: "packer/aws/ubuntu/20_04/init.sh"

      - name: Copy inventory.sh
        with:
          source: "scripts/inventory.sh"
          target: "packer/aws/ubuntu/20_04/inventory.sh"

      - name: Copy kind-load-cafile.sh
        with:
          source: "scripts/kind-load-cafile.sh"
          target: "packer/aws/ubuntu/20_04/kind-load-cafile.sh"

      - name: Copy fetch-tanzu-cli.sh
        with:
          source: "scripts/fetch-tanzu-cli.sh"
          target: "packer/aws/ubuntu/20_04/fetch-tanzu-cli.sh"

      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@v1

      - name: Initialize Packer
        working-directory: ./packer/aws/ubuntu/20_04
        run: packer init .

      - name: Build image from template
        working-directory: ./packer/aws/ubuntu/20_04
        run: packer build -only=standard .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
