name: Build Ubuntu 21.04 Container Image with Docker

on:
  - pull_request

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Make dist directory
        run: |
          mkdir -p dist

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/
          push: false
          tags: tanzu/k8s-toolset:latest
