name: Build Ubuntu 21.04 Container Image with Docker

on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and tag container image
        run: |
          mkdir -p dist
          docker build --file docker/Dockerfile --tag tanzu/k8s-toolset .
